resume_path: input/Resume_Faizan_2023.pdf
technical_fields: {
    "CV": [
        "opencv",
        "tensorflow",
        "pytorch",
        "image classification",
        "image segmentation",
        "object detection",
    ],
    "NLP": [
        "nlp", 
        "transformer",
        "encoder decoder",
        "bert",
        "text analysis",
        "sentiment analysis",
        "chatbot",
        "pytorch",
        "NLTK",
        "sequence model",
        "text mining",
    ],
    "Tradition ML": [
        "python",
        "matplotlib",
        "scikit learn",
        "regression",
        "numpy",
        "pandas",
    ],
    "Other skills": ["python", "git", "docker"],
}
